### ISSUE TITLE
Advanced statistics on Profit Margin Calculator

### ISSUE THREAD

**Issue by ajaxify** [Ravworks/Ravworks.com#19]
Would be helpful to see some other statistics on the Profit Margin page, including:

- Avg daily or weekly volume in Jita (or configurable trade hub)
- Product of the weekly sales number and the expected profit to estimate total sales volume.
- Estimate of isk/slot-hr

To avoid a "wall of numbers" problem:
- Advanced statistics page
- Columns selectable as part of the config

Original discord convo: https://discord.com/channels/773370689376878592/781881817439404032/824711692104761385

**Comment by Ravworks** [comment]
Added a daily market volume (average over the last week), and a isk/hour column.

Decided to just make the table wider for now.
